# In .github/workflows/mega-linter.yml
name: Mega-Linter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  megalinter:
    name: Mega-Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Mega-Linter
        uses: oxsecurity/megalinter@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
